### ISSUE TITLE
Undefined index 'editor_mode'

### ISSUE THREAD

**Issue by jomurgel** [qTranslate-Team/wp-seo-qtranslate-x#2]
Notice: Undefined index: editor_mode in ../wp-content/plugins/wp-seo-qtranslate-x/wordpress-seo-qtranslate-x.php on line 26

**Comment by johnclause** [comment]
Are you using the latest qtx?

**Comment by jomurgel** [comment]
Sorry.  Updated to latest qtx fixed the issue.
