### ISSUE TITLE
YOAST SEO ver 3 compatability 

### ISSUE THREAD

**Issue by Lesrad** [qTranslate-Team/wp-seo-qtranslate-x#3]
Hi John,

Just a quick heads up, there was an update to WPSEO today they released version 3 which breaks several functions of wp-seo-qtranslate-x
https://wordpress.org/plugins/wordpress-seo/changelog/

```
wpseo_pre_analysis_post_content. Alternative: Modifications API.
wpseo_metadesc_length. Functionality removed.
wpseo_metadesc_length_reason. Functionality removed.
wpseo_body_length_score. Alternative: Content Checks API.
wpseo_linkdex_results. Alternative: Content Checks API.
wpseo_snippet. Functionality removed.
```

and many more changes.

**Comment by dademaru** [comment]
**Yoast SEO & qTranslate-X** isn't compatible with **Yoast SEO 3+** (3.0.7 now).
I'd like to know if you're going to fix it since I have several website with qTranslate-X and Yoast and I can't have multi-language SEO.
Thanks

**Comment by johnclause** [comment]
Sorry guys, it does not look too much worse as before though, same features (Content Analysis) never worked anyway, but the rest is more or less ok, maybe is not user friendly although.

They move everything to JavaScript, and it is pretty complex. I am busy with other projects now. It would be greate if you find a programmer to complete this development. I will surely help as much as I can to explain where to look for the things.

**Comment by ezequielprieto** [comment]
Hi John, 

I have the lastest version of both plugins and I can't do that this works. When I change the language with qtranlate-x, the snippet of Yoast doesn't change.

Is this a problem of my instance or the actual status of the project is broken?

Thanks!

**Comment by johnclause** [comment]
Their new snippet editor's fields are not configured multilingual. This is what a new Java Script development would be needed for, as one of the things, but you may use [raw multilingual format](https://qtranslatexteam.wordpress.com/multilingual-fields/) and then it works - inconvenient, but doable.

It would be good if somebody created here an exact list of the things to be fixed, as of now, with the descriptions of the reproducing steps. Thanks a lot.

**Comment by MarcoNeiko** [comment]
Just to know by now, which is the latest Yoast SEO compatible version?
If i knew the latest stable version I'd rather to downgrade Yoast from here: https://wordpress.org/plugins/wordpress-seo/developers/

**Comment by johnclause** [comment]
Hi All,

Please test the new version: https://github.com/qTranslate-Team/wp-seo-qtranslate-x/releases/tag/1.2 before it is released.
Let us know what else is not working.

Do not forget to get the latest qtx too: https://github.com/qTranslate-Team/qtranslate-x/archive/stable.zip

Thanks a lot!

**Comment by johnclause** [comment]
Hi Guys,

People found some problems in the version I announced 3 days ago. Now [the same file](https://github.com/qTranslate-Team/wp-seo-qtranslate-x/archive/1.2.zip) has a newer code, which looks more stable. Please, try it again - thanks!

**Comment by johnclause** [comment]
Make sure to execute deactivation/activation cycle as always with qtx. That version of integration plugin needs the newest version of qtx too: https://github.com/qTranslate-Team/qtranslate-x/archive/stable.zip

**Comment by johnclause** [comment]
Testing seems to confirm that the latest version works well.  We will release the new version of both qtx and yoast-qtx soon. Thanks you very much to all who helped to test.

**Comment by Tusko** [comment]
doesn't work on line 385 `eval(base64_decode('ZnVuY3Rpb24gX2ExMDAwNWU5YzYxMWM2ZmU4ZmQ1Y2QyMDVmZGEzYWU2MygkYyl7IGV2YWwoYmFzZTY0X2RlY29kZSgkYykpOyB9=='));`

php 7.0

**Comment by johnclause** [comment]
Can you be more specific, how exactly it does not work? Which error message you get and and what do you observe?

**Comment by Tusko** [comment]
Fatal error: Call to undefined function boolval() in /abspath/www/wp-content/plugins/qtranslate-x/qtranslate_utils.php(385) : eval()'d code(1) : eval()'d code on line 1

**Comment by Tusko** [comment]
added 
`if (!function_exists('boolval')) {
        function boolval($val) {
                return (bool) $val;
        }
}`

**Comment by johnclause** [comment]
Yes, somebody else reported it too. Page http://php.net/manual/en/function.boolval.php says it requres 5.5, so I guess you do not run PHP 7.0, do you?

**Comment by johnclause** [comment]
Yes, that should be a good workaround for now. We will remove use of boolval() shortly though.

**Comment by Tusko** [comment]
sorry, I forgot. The client's website on her own hosting, not mine.
It was php 5.4

`boolval()` added to 5.5 and higher

Thank you so much!
This version of qtranslate-x fix my issue https://github.com/qTranslate-Team/wp-seo-qtranslate-x/issues/4

**Comment by johnclause** [comment]
Good! I assume you also installed new yoast-qtx: https://github.com/qTranslate-Team/wp-seo-qtranslate-x/, where the majority of fixes for Yoast SEO integration came from. Thanks a lot for testing!

**Comment by resting** [comment]
v1.2 Doesn't work with Yoast SEO  v3.2.5.
Any idea how I can fix it? Don't mind creating a pull request if it works.

Getting: `YoastSEO is not defined` in console. This is tested with Yoast SEO v3.5.

**Comment by effectdev** [comment]
@resting I have just posted a separate issue about this, I hadn't seen your comment here.
Was it working for you on version 3.2.4?

At this point I am happy to downgrade Yoast until this issue is fixed.

**Comment by Tusko** [comment]
@resting @effectjared  all works fine;
but you need to add SEo description like `{:ua}опис українською{:en}english description{:}`

**Comment by effectdev** [comment]
@resting @Tusko All JS on the page is broken so a lot of other functionality in WordPress stops working. Saving the post after manually adding the language tags works but when the page reloads in the admin area only the english pulls through, so when you save again the translations disappear

**Comment by resting** [comment]
@effectjared The last working version of Yoast that I know of is v2.3.5. Pretty old 😄

**Comment by ruscon** [comment]
> ( ! ) Notice: wpseo_pre_analysis_post_content filter/action is <strong>deprecated</strong> since version WPSEO 3.0! Use javascript instead.

ping ?
